"""remove country column

Revision ID: 04ea97f1789a
Revises: 2961c55d25f3
Create Date: 2025-12-30 10:09:29.505064

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04ea97f1789a"
down_revision: Union[str, Sequence[str], None] = "2961c55d25f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c["name"] for c in inspector.get_columns("books")]
    if "country" in columns:
        op.drop_column("books", "country")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books", sa.Column("country", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
