"""Add is_owned column

Revision ID: cb1dd1bad822
Revises: 04ea97f1789a
Create Date: 2026-01-03 12:26:52.330720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1dd1bad822'
down_revision: Union[str, Sequence[str], None] = '04ea97f1789a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('is_owned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'is_owned')
    # ### end Alembic commands ###
